export type InventorySummary = { products: Array<{ id: string; name: string; variants: Array<{ id: string; label: string; available: number; awaiting_payment: number; under_review: number; confirmed: number; fulfilled: number }> }> };

export function ProductSizeSummary({ summary }: { summary: InventorySummary }) {
  return <section className="space-y-4" aria-label="Product size breakdown"><div><h2 className="text-xl font-semibold">Products & sizes</h2><p className="mt-1 text-sm text-slate-500">Paid unit counts by option. A size is counted only after you approve its UPI payment; pending payments are shown separately.</p></div>{summary.products.map((product) => {
    const ordered = (variant: typeof product.variants[number]) => variant.confirmed + variant.fulfilled;
    const pending = (variant: typeof product.variants[number]) => variant.awaiting_payment + variant.under_review;
    const total = product.variants.reduce((sum, variant) => sum + ordered(variant), 0);
    const available = product.variants.reduce((sum, variant) => sum + variant.available, 0);
    const max = Math.max(1, ...product.variants.map(ordered));
    return <details key={product.id} open className="rounded-2xl border bg-white p-4 sm:p-5"><summary className="cursor-pointer"><span className="font-semibold">{product.name}</span><span className="ml-3 inline-block text-sm text-slate-500">{total} paid · {available} available</span></summary><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[640px] text-left text-sm"><caption className="sr-only">{product.name} quantities by option or size</caption><thead className="border-b text-xs text-slate-500"><tr>{["Option / size", "Paid", "Pending verification", "Ready for pickup", "Collected", "Available"].map((label) => <th key={label} scope="col" className="px-3 py-3 font-medium first:pl-0">{label}</th>)}</tr></thead><tbody className="divide-y">{product.variants.map((variant) => <tr key={variant.id}><th scope="row" className="min-w-24 py-3 pr-3 font-medium">{variant.label}<div aria-hidden="true" className="mt-2 h-1 w-20 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-slate-800" style={{ width: `${ordered(variant) / max * 100}%` }} /></div></th>{[ordered(variant), pending(variant), variant.confirmed, variant.fulfilled].map((value, index) => <td key={index} className="px-3 py-3 tabular-nums">{value}</td>)}<td className={`px-3 py-3 tabular-nums ${variant.available === 0 ? "font-medium text-amber-700" : "text-emerald-700"}`}>{variant.available === 0 ? "0 · Sold out" : variant.available}</td></tr>)}</tbody></table></div><p className="mt-3 text-xs text-slate-400 sm:hidden">Swipe sideways to see all counts.</p></details>;
  })}</section>;
}
