import { useEffect, useState } from "react";
import { AdminDashboardLayout } from "@/components/AdminDashboardLayout";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { apiRequest } from "@/lib/api";

type Mode = "DEFAULT" | "CUSTOM_PERCENTAGE" | "FIXED_PER_PARTICIPANT";
type Org = { organizationId: string; organizationName: string; status: string; platformPricing: { mode: Mode; percentageBasisPoints: number; minimumFeePaise: number; maximumFeePaise: number; fixedFeePaise: number | null } };
export default function AdminOrganizerPricing() {
  const [orgs, setOrgs] = useState<Org[]>([]); const [draft, setDraft] = useState<Record<string, { mode: Mode; percentage: string; minimum: string; maximum: string; fixed: string }>>({}); const [message, setMessage] = useState("");
  useEffect(() => { void apiRequest<Org[]>("/admin/organizers").then(rows => { setOrgs(rows); setDraft(Object.fromEntries(rows.map(o => [o.organizationId, { mode: o.platformPricing.mode, percentage: String(o.platformPricing.percentageBasisPoints / 100), minimum: String(o.platformPricing.minimumFeePaise / 100), maximum: String(o.platformPricing.maximumFeePaise / 100), fixed: String((o.platformPricing.fixedFeePaise ?? 2000) / 100) }]))); }); }, []);
  const save = async (org: Org) => { const d = draft[org.organizationId]; await apiRequest(`/admin/organizers/${org.organizationId}/platform-pricing`, { method: "PUT", body: JSON.stringify({ mode: d.mode, percentage_basis_points: d.mode === "CUSTOM_PERCENTAGE" ? Math.round(Number(d.percentage) * 100) : null, minimum_fee_paise: d.mode === "CUSTOM_PERCENTAGE" ? Math.round(Number(d.minimum) * 100) : null, maximum_fee_paise: d.mode === "CUSTOM_PERCENTAGE" ? Math.round(Number(d.maximum) * 100) : null, fixed_fee_paise: d.mode === "FIXED_PER_PARTICIPANT" ? Math.round(Number(d.fixed) * 100) : null }) }); setMessage("Saved. Pricing changes apply only to future registrations."); };
  return <AdminDashboardLayout><div className="mx-auto max-w-4xl space-y-5 px-4 py-8"><h1 className="text-3xl font-black">Organizer SportPass pricing</h1><p className="text-sm text-muted-foreground">Choose how SportPass Credits are charged for each organizer. Changes apply only to future registrations.</p>{orgs.map(org => { const d = draft[org.organizationId]; const choose = (mode: Mode) => setDraft(x => ({ ...x, [org.organizationId]: { ...d, mode } })); return <Card key={org.organizationId}><CardHeader><CardTitle>{org.organizationName}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-3"><button type="button" className={`rounded-lg border p-4 text-left ${d?.mode === "DEFAULT" ? "border-primary bg-primary/5" : ""}`} onClick={() => choose("DEFAULT")}><p className="font-semibold">Default pricing</p><p className="text-sm text-muted-foreground">4% per registration, minimum ₹20 and maximum ₹60.</p></button><button type="button" className={`rounded-lg border p-4 text-left ${d?.mode === "CUSTOM_PERCENTAGE" ? "border-primary bg-primary/5" : ""}`} onClick={() => choose("CUSTOM_PERCENTAGE")}><p className="font-semibold">Custom percentage</p><p className="text-sm text-muted-foreground">Set a special percentage and fee limits.</p></button>{d?.mode === "CUSTOM_PERCENTAGE" && <div className="grid gap-3 rounded-lg bg-muted/30 p-4 sm:grid-cols-3"><Input value={d.percentage} onChange={e => setDraft(x => ({ ...x, [org.organizationId]: { ...d, percentage: e.target.value } }))} placeholder="Percentage" /><Input value={d.minimum} onChange={e => setDraft(x => ({ ...x, [org.organizationId]: { ...d, minimum: e.target.value } }))} placeholder="Minimum ₹" /><Input value={d.maximum} onChange={e => setDraft(x => ({ ...x, [org.organizationId]: { ...d, maximum: e.target.value } }))} placeholder="Maximum ₹" /></div>}<button type="button" className={`rounded-lg border p-4 text-left ${d?.mode === "FIXED_PER_PARTICIPANT" ? "border-primary bg-primary/5" : ""}`} onClick={() => choose("FIXED_PER_PARTICIPANT")}><p className="font-semibold">Fixed fee per participant</p><p className="text-sm text-muted-foreground">Charge the same Credit amount for every participant.</p></button>{d?.mode === "FIXED_PER_PARTICIPANT" && <div className="rounded-lg bg-muted/30 p-4"><Input value={d.fixed} onChange={e => setDraft(x => ({ ...x, [org.organizationId]: { ...d, fixed: e.target.value } }))} placeholder="Fixed fee ₹" /></div>}</div><Button onClick={() => void save(org)}>Save pricing</Button></CardContent></Card>; })}{message && <p className="text-sm text-muted-foreground">{message}</p>}</div></AdminDashboardLayout>;
}
